#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-bonecp
Version  : 0.8.0
Release  : 1
URL      : https://github.com/wwadge/bonecp/archive/bonecp-parent-0.8.0.RELEASE.tar.gz
Source0  : https://github.com/wwadge/bonecp/archive/bonecp-parent-0.8.0.RELEASE.tar.gz
Source1  : https://repo1.maven.org/maven2/com/jolbox/bonecp-parent/0.8.0.RELEASE/bonecp-parent-0.8.0.RELEASE.pom
Source2  : https://repo1.maven.org/maven2/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.jar
Source3  : https://repo1.maven.org/maven2/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-bonecp-data = %{version}-%{release}

%description
BoneCP Targets JDK 1.5, 1.6 and 1.7. You will have to select the target compiler you wish via profiles eg:

%package data
Summary: data components for the mvn-bonecp package.
Group: Data

%description data
data components for the mvn-bonecp package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp-parent/0.8.0.RELEASE
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp-parent/0.8.0.RELEASE/bonecp-parent-0.8.0.RELEASE.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/jolbox/bonecp-parent/0.8.0.RELEASE/bonecp-parent-0.8.0.RELEASE.pom
/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.jar
/usr/share/java/.m2/repository/com/jolbox/bonecp/0.8.0.RELEASE/bonecp-0.8.0.RELEASE.pom
